language: generic
dist: xenial
os: linux

git:
  depth: 1

jobs:
  include:
    - name: "Run Linters"
      addons:
        apt:
          packages:
            - python3
            - python3-pip
            - python3-setuptools
      install:
        - chmod +x tools/travis/install_build_deps.sh
        - chmod +x tools/travis/install_dreamchecker.sh
      script:
        - shopt -s globstar
        - find . -name "*.php" -print0 | xargs -0 -n1 php -l
        - find . -name "*.json" -not -path "./nano/node_modules/*" -print0 | xargs -0 python3 ./tools/travis/json_verifier.py
        - chmod +x tools/travis/build_nanoui.sh
        - chmod +x tools/travis/check_grep.sh
        - tools/travis/check_changelogs.sh
        - python3 tools/travis/check_line_endings.py

    - name: "Compile All Maps"
      addons:
        apt:
          packages:
            - libstdc++6:i386
      cache:
        directories:
          - $HOME/BYOND
      install:
        - chmod +x tools/travis/install_byond.sh
        - source $HOME/BYOND/byond/bin/byondsetup
      script:
        - tools/travis/dm.sh -Mtravis_map_testing paradise.dme
